# Listen directives
listen=YES
listen_port=21
listen_address=0.0.0.0
seccomp_sandbox=NO

# Enable
anonymous_enable=NO
local_enable=YES
write_enable=YES
port_enable=YES

# Root
chroot_local_user=YES
allow_writeable_chroot=YES
local_root=/var/www/html/wp-content/uploads

# userlist
userlist_enable=YES
userlist_file=/etc/vsftpd.userlist
userlist_deny=NO

# Passive mod
pasv_enable=YES
pasv_min_port=10000
pasv_max_port=10010

# Logs
dirmessage_enable=YES
use_localtime=YES
xferlog_enable=YES