server {
	listen		443 ssl;
	server_name	sliziard.42.fr;

	root		/var/www/html;
	index		index.php index.html index.htm;

	ssl_protocols		TLSv1.2 TLSv1.3;
	ssl_certificate		/etc/nginx/ssl/inception.crt;
	ssl_certificate_key	/etc/nginx/ssl/inception.key;

	location / {
		try_files $uri $uri/ /index.php?$args;
	}

	location /favicon.ico {
		log_not_found off;
		access_log off;
	}

	location ~ \.php$ {
		include snippets/fastcgi-php.conf;
		fastcgi_pass wordpress:9000;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		include fastcgi_params;
	}

	location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
		expires max;
		log_not_found off;
	}
}
