services:
    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb
        image: mariadb
        env_file: .env
        volumes:
            - mariadb_data:/var/lib/mysql
        networks:
            - inception
        secrets:
          - mysql_root_password
          - mysql_password
        restart: always
        healthcheck:
          test: ["CMD", "nc", "-zv", "127.0.0.1", "3306"]
          interval: 1s
          timeout: 5s
          retries: 10
    
    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress
        image: wordpress
        env_file: .env
        volumes:
            - wordpress_data:/var/www/html
        networks:
            - inception
        depends_on:
            mariadb:
              condition: service_healthy
        secrets:
          - mysql_password
          - wp_admin_password
          - wp_user_password
        restart: always
        healthcheck:
            test: ["CMD", "nc", "-zv", "localhost", "9000"]
            interval: 5s
            timeout: 4s
            retries: 10
    
    nginx:
        container_name: nginx
        build:
            context: ./requirements/nginx
            args:
              DOMAIN_NAME: ${DOMAIN_NAME}
        image: nginx
        env_file: .env
        volumes:
            - ssl_certs_data:/etc/nginx/ssl
            - wordpress_data:/var/www/html
        ports:
            - "443:443"
        networks:
            inception:
                aliases:
                  - sliziard.42.fr
        depends_on:
            wordpress:
              condition: service_healthy
            static_site:
              condition: service_completed_successfully
        restart: always

    redis:
        container_name: redis
        build: ./requirements/redis
        image: redis
        restart: unless-stopped
        networks:
            - inception

    adminer:
        container_name: adminer
        build: ./requirements/adminer
        image: adminer
        restart: unless-stopped
        networks:
            - inception

    vsftpd:
        container_name: vsftpd
        build: ./requirements/vsftpd
        image: vsftpd
        restart: unless-stopped
        environment:
            FTP_USER: ${FTP_USER}
            FTP_PWD: ${FTP_PWD}
        ports:
            - "21:21"
            - "10000-10010:10000-10010"
        volumes:
            - wordpress_data:/var/www/html
        networks:
            - inception

    static_site:
        container_name: static_site
        build: ./requirements/static-site
        image: static_site
        restart: on-failure
        volumes:
            - wordpress_data:/var/www/html
        networks:
            - inception

    filestash:
        container_name: filestash
        build: ./requirements/filestash
        image: filestash
        restart: unless-stopped
        ports:
          - "8334:8334"
        volumes:
          - filestash_data:/app/data/state/
          - ssl_certs_data:/usr/local/share/ca-certificates
        environment:
          - STORAGE_TYPE=ftp
          - STORAGE_FTP_HOST=vsftpd
          - STORAGE_FTP_PORT=21
          - STORAGE_FTP_USER=${FTP_USER}
          - STORAGE_FTP_PASS=${FTP_PWD}
          - STORAGE_FTP_ROOT=/var/www/html
        networks:
          - inception
        depends_on:
          - vsftpd

volumes:
    ssl_certs_data:
      driver: local
      driver_opts:
        type: none
        device: ~/42/inception/data/certs
        o: bind

    mariadb_data:
      driver: local
      driver_opts:
        type: none
        device: ~/42/inception/data/mariadb
        o: bind

    wordpress_data:
      driver: local
      driver_opts:
        type: none
        device: ~/42/inception/data/wordpress
        o: bind
    
    filestash_data:
      driver: local
      driver_opts:
        type: none
        device: ~/42/inception/data/filestash
        o: bind

networks:
    inception:
        driver: bridge

secrets:
  mysql_password:
    file: ../secrets/mysql_password.txt
  mysql_root_password:
    file: ../secrets/mysql_root_password.txt

  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt