services:
    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb
        image: mariadb
        env_file: .env
        volumes:
            - mariadb_data:/var/lib/mysql
        networks:
            - inception
        secrets:
          - mysql_root_password
          - mysql_password
        restart: always
        healthcheck:
          test: ["CMD", "nc", "-zv", "mariadb", "3306"]
          interval: 1s
          timeout: 5s
          retries: 10
    
    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress
        image: wordpress
        env_file: .env
        volumes:
            - wordpress_data:/var/www/html
        networks:
            - inception
        depends_on:
            - mariadb
        secrets:
          - mysql_password
          - wp_admin_password
          - wp_user_password
        restart: always
    
    nginx:
        container_name: nginx
        build: ./requirements/nginx
        image: nginx
        env_file: .env
        volumes:
            - wordpress_data:/var/www/html
        ports:
            - "443:443"
        networks:
            - inception
        depends_on:
            - wordpress
        restart: always

volumes:
    mariadb_data:
      driver: local
      driver_opts:
        type: none
        device: /home/sliziard/data/mariadb
        o: bind

    wordpress_data:
      driver: local
      driver_opts:
        type: none
        device: /home/sliziard/data/wordpress
        o: bind

networks:
    inception:
        driver: bridge

secrets:
  mysql_password:
    file: ../secrets/mysql_password.txt
  mysql_root_password:
    file: ../secrets/mysql_root_password.txt

  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt